name: Deploy .NET API to Azure Web App

on:
  push:
    branches: [ master ]
    paths:
      - 'apps/api/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore apps/api
      
    - name: Build application
      run: dotnet build apps/api --configuration Release --no-restore
      
    - name: Publish application
      run: dotnet publish apps/api --configuration Release --no-build --output ./publish
      
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'fullstack-app'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './publish'
